import authRoutes from "../modules/auth/auth.routes.js";
import userRoutes from "../modules/users/user.routes.js";
import barangayRoutes from "../modules/barangays/barangay.routes.js";
import patientRoutes from "../modules/patients/patient.routes.js";
import medicationLogRoutes from "../modules/medication-logs/medication-log.routes.js";
import symptomLogRoutes from "../modules/symptom-logs/symptom-log.routes.js";
import appointmentRoutes from "../modules/appointments/appointment.routes.js";
import sputumTestRoutes from "../modules/sputum-tests/sputum-test.routes.js";
import inventoryRoutes from "../modules/inventory/inventory.routes.js";
import stockAllocationRoutes from "../modules/stock-allocations/stock-allocation.routes.js";
import dispensingRoutes from "../modules/dispensing/dispensing.routes.js";
import complianceRoutes from "../modules/compliance/compliance.routes.js";
import alertRoutes from "../modules/alerts/alert.routes.js";
import escalationRoutes from "../modules/escalations/escalation.routes.js";
import heatmapRoutes from "../modules/heatmap/heatmap.routes.js";
import notificationRoutes from "../modules/notifications/notification.routes.js";
import reportRoutes from "../modules/reports/report.routes.js";

export default (app) => {
  app.use("/api/auth", authRoutes);
  app.use("/api/users", userRoutes);
  app.use("/api/barangays", barangayRoutes);
  app.use("/api/patients", patientRoutes);
  app.use("/api/medication-logs", medicationLogRoutes);
  app.use("/api/symptom-logs", symptomLogRoutes);
  app.use("/api/appointments", appointmentRoutes);
  app.use("/api/sputum-tests", sputumTestRoutes);
  app.use("/api/inventory", inventoryRoutes);
  app.use("/api/stock-allocations", stockAllocationRoutes);
  app.use("/api/dispensing", dispensingRoutes);
  app.use("/api/compliance", complianceRoutes);
  app.use("/api/alerts", alertRoutes);
  app.use("/api/escalations", escalationRoutes);
  app.use("/api/heatmap", heatmapRoutes);
  app.use("/api/notifications", notificationRoutes);
  app.use("/api/reports", reportRoutes);
};
