// ============================================================
// scripts/seedMockStaff.js
//
// One-time defense-prep seed: wipes existing super_admin / patc /
// barangay_admin / nurse accounts and replaces them with a clean,
// presentable set of mock accounts across 3 real Pasig barangays
// (Caniogan / Bambang / Pinagbuhatan — looked up by name from the
// barangays collection, not hardcoded IDs, since those are
// auto-generated by seedPasigHealthCenters.js). Patients and other
// collections are left untouched — this script only touches
// staff-role users.
//
// Run with: node src/scripts/seedMockStaff.js
// (run seedPasigHealthCenters.js first so these barangays exist)
// ============================================================

import mongoose from "mongoose";
import bcrypt from "bcryptjs";
import "dotenv/config";

const { MONGODB_URI } = process.env;

const DEFAULT_PASSWORD = "Passw0rd!";

// Barangay names to pull staff assignments for — each barangay's
// FIRST health center (by insertion order) is used.
const TARGET_BARANGAYS = ["Caniogan", "Bambang", "Pinagbuhatan"];

async function loadBarangayRefs(db) {
  const docs = await db.collection("barangays").find({ name: { $in: TARGET_BARANGAYS } }).toArray();
  const byName = {};
  for (const name of TARGET_BARANGAYS) {
    const doc = docs.find((d) => d.name === name);
    if (!doc) throw new Error(`Barangay "${name}" not found — run seedPasigHealthCenters.js first.`);
    const center = doc.health_centers?.[0];
    if (!center) throw new Error(`Barangay "${name}" has no health centers.`);
    byName[name] = {
      barangay_id: doc.barangay_id,
      barangay_name: doc.name,
      health_center_id: center.health_center_id,
    };
  }
  return byName;
}

// ── Run ──────────────────────────────────────────────────────

async function nextUserId(startFrom) {
  return `USR-${String(startFrom).padStart(4, "0")}`;
}

async function run() {
  await mongoose.connect(MONGODB_URI);
  const db = mongoose.connection;
  const users = db.collection("users");

  const BARANGAYS = await loadBarangayRefs(db);

  const STAFF = [
    // Super Admin
    {
      role: "super_admin",
      first_name: "Rafael",
      last_name: "Villanueva",
      email: "superadmin@respiratrack.ph",
      phone_number: "+639171234501",
    },

    // PATC (Pasig Treatment Center)
    {
      role: "patc",
      first_name: "Corazon",
      last_name: "Mendoza",
      email: "patc.admin@respiratrack.ph",
      phone_number: "+639171234502",
    },

    // Barangay (Health Center) Admins — one per barangay
    {
      role: "barangay_admin",
      first_name: "Liza",
      last_name: "Fernandez",
      email: "admin.caniogan@respiratrack.ph",
      phone_number: "+639171234511",
      ...BARANGAYS["Caniogan"],
    },
    {
      role: "barangay_admin",
      first_name: "Noel",
      last_name: "Ramos",
      email: "admin.bambang@respiratrack.ph",
      phone_number: "+639171234512",
      ...BARANGAYS["Bambang"],
    },
    {
      role: "barangay_admin",
      first_name: "Teresita",
      last_name: "Aquino",
      email: "admin.pinagbuhatan@respiratrack.ph",
      phone_number: "+639171234513",
      ...BARANGAYS["Pinagbuhatan"],
    },

    // Nurses (Health Workers) — two per barangay
    {
      role: "nurse",
      first_name: "Angelica",
      last_name: "Torres",
      email: "nurse.caniogan1@respiratrack.ph",
      phone_number: "+639171234521",
      ...BARANGAYS["Caniogan"],
    },
    {
      role: "nurse",
      first_name: "Joshua",
      last_name: "Bautista",
      email: "nurse.caniogan2@respiratrack.ph",
      phone_number: "+639171234522",
      ...BARANGAYS["Caniogan"],
    },
    {
      role: "nurse",
      first_name: "Kristine",
      last_name: "Reyes",
      email: "nurse.bambang1@respiratrack.ph",
      phone_number: "+639171234523",
      ...BARANGAYS["Bambang"],
    },
    {
      role: "nurse",
      first_name: "Michael",
      last_name: "Garcia",
      email: "nurse.bambang2@respiratrack.ph",
      phone_number: "+639171234524",
      ...BARANGAYS["Bambang"],
    },
    {
      role: "nurse",
      first_name: "Bea",
      last_name: "Domingo",
      email: "nurse.pinagbuhatan1@respiratrack.ph",
      phone_number: "+639171234525",
      ...BARANGAYS["Pinagbuhatan"],
    },
    {
      role: "nurse",
      first_name: "Paolo",
      last_name: "Santiago",
      email: "nurse.pinagbuhatan2@respiratrack.ph",
      phone_number: "+639171234526",
      ...BARANGAYS["Pinagbuhatan"],
    },
  ];

  const wipeRoles = ["super_admin", "patc", "barangay_admin", "nurse"];
  const { deletedCount } = await users.deleteMany({ role: { $in: wipeRoles } });
  console.log(`🗑️  Removed ${deletedCount} existing staff accounts (${wipeRoles.join(", ")}).`);

  // Find the current highest USR-#### among remaining users (e.g. patients)
  // so new IDs don't collide.
  const remaining = await users.find({}, { projection: { user_id: 1 } }).toArray();
  const nums = remaining
    .map((u) => parseInt(u.user_id?.split("-")[1], 10))
    .filter((n) => !isNaN(n));
  let seq = (nums.length ? Math.max(...nums) : 0) + 1;

  const now = new Date();
  const docs = [];
  for (const staff of STAFF) {
    const password_hash = await bcrypt.hash(DEFAULT_PASSWORD, 12);
    docs.push({
      user_id: await nextUserId(seq++),
      role: staff.role,
      first_name: staff.first_name,
      last_name: staff.last_name,
      email: staff.email,
      password_hash,
      phone_number: staff.phone_number,
      barangay_id: staff.barangay_id || null,
      barangay_name: staff.barangay_name || null,
      health_center_id: staff.health_center_id || null,
      phone_verified: false,
      is_active: true,
      created_at: now,
      updated_at: now,
    });
  }

  await users.insertMany(docs);
  console.log(`✅ Inserted ${docs.length} mock staff accounts.\n`);

  console.log("Login credentials:");
  for (const d of docs) {
    console.log(`  [${d.role.padEnd(14)}] ${d.email.padEnd(32)} pw: ${DEFAULT_PASSWORD.padEnd(12)} ${d.user_id}  ${d.barangay_name ? `(${d.barangay_name})` : ""}`);
  }

  await mongoose.connection.close();
}

run().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});
