// ============================================================
// models/Alert.js
// Covers: Tablet Module 6 — Alerts Screen
//         Web dashboard latest alerts card
//         Add 2 — Escalation alert records
//
// Distinct from escalation_logs — alerts are the real-time
// event surface that staff sees and acts on. escalation_logs
// is the permanent audit trail of what happened and when.
// ============================================================

import mongoose from "mongoose";

const { Schema, model } = mongoose;

const AlertSchema = new Schema(
  {
    // ── Identifiers ────────────────────────────────────────
    alert_id: {
      type: String,
      required: true,
      unique: true,
      trim: true,
      // Format: "ALT-{barangay_id}-{timestamp_ms}"
      // e.g.  "ALT-BRG001-1704067200000"
      // Generated by the service layer before saving
    },

    patient_id: {
      type: String,
      required: true,
      trim: true,
      ref: "Patient",
    },

    tb_case_number: {
      type: String,
      required: true,
      trim: true,
      // "PHNT-1304-071-S26-0001"
    },

    barangay_id: {
      type: String,
      required: true,
      trim: true,
      ref: "Barangay",
    },

    // ── Alert classification ───────────────────────────────
    alert_type: {
      type: String,
      required: true,
      enum: [
        "Missed Dose",
        "Escalation L1",
        "Escalation L2",
        "Escalation L3",
        "Low Stock",
        "Stock Request", // ← new: fires when a new patient is registered at a health center
        "Sputum Test Due", // sputum test approaching (3 days before due_date)
        "Sputum Sample Submitted", // patient self-reported handing in a sample
        "Appointment Reminder", // 24h before scheduled appointment
        "Contact Info Updated", // patient changed their phone number or email
      ],
    },

    // 0 if not an escalation alert, 1–3 if escalation type
    escalation_level: {
      type: Number,
      enum: [0, 1, 2, 3],
      default: 0,
    },

    severity: {
      type: String,
      required: true,
      enum: ["Info", "Warning", "Critical"],
      default: "Info",
    },

    // ── Content ────────────────────────────────────────────
    message: {
      type: String,
      required: true,
      trim: true,
      maxlength: 500,
      // e.g. "Patient PHNT-1304-071-S26-0001 has missed 2 consecutive doses."
    },

    // ── Audience ───────────────────────────────────────────
    // Which roles this alert is visible to in their alert screens
    target_roles: {
      type: [String],
      required: true,
      enum: ["super_admin", "barangay_admin", "nurse", "patc"],
      validate: {
        validator: (arr) => arr.length > 0,
        message: "At least one target role is required.",
      },
    },

    // ── Lifecycle ──────────────────────────────────────────
    status: {
      type: String,
      required: true,
      enum: ["Active", "Acknowledged", "Resolved"],
      default: "Active",
    },

    // Optional cross-reference back to escalation_logs
    // Populated only when alert_type is Escalation L1/L2/L3
    escalation_id: {
      type: String,
      default: null,
      trim: true,
      ref: "EscalationLog",
    },

    resolved_by: {
      type: String,
      default: null,
      trim: true,
      ref: "User",
      // user_id of the staff member who resolved this alert
    },

    resolved_at: {
      type: Date,
      default: null,
    },

    resolution_notes: {
      type: String,
      default: "",
      trim: true,
      maxlength: 500,
    },
  },
  {
    timestamps: {
      createdAt: "created_at",
      updatedAt: "updated_at",
    },
    collection: "alerts",
  },
);

// ── Indexes ────────────────────────────────────────────────
// Compound indexes that match your most common query patterns

// Staff alert screen: fetch active alerts for my barangay, newest first
AlertSchema.index({ barangay_id: 1, status: 1, created_at: -1 });

// Super admin dashboard: fetch all active Critical/Warning alerts
AlertSchema.index({ status: 1, severity: 1, created_at: -1 });

// Patient-specific alert lookup (escalation workflow)
AlertSchema.index({ patient_id: 1, status: 1 });

// tb_case_number lookup
AlertSchema.index({ tb_case_number: 1 });

// Alert type filtering (e.g. show only Escalation alerts)
AlertSchema.index({ alert_type: 1, status: 1 });

// Role-based filtering
AlertSchema.index({ target_roles: 1, status: 1 });

// ── Virtuals ───────────────────────────────────────────────
// Convenience flag — true if alert has been sitting Active
// for more than 24 hours without acknowledgement
AlertSchema.virtual("is_overdue").get(function () {
  if (this.status !== "Active") return false;
  const msElapsed = Date.now() - new Date(this.created_at).getTime();
  return msElapsed > 24 * 60 * 60 * 1000;
});

// ── Instance methods ───────────────────────────────────────
// Acknowledge an alert (moves it from Active → Acknowledged)
AlertSchema.methods.acknowledge = async function (userId) {
  if (this.status === "Resolved") {
    throw new Error("Cannot acknowledge a resolved alert.");
  }
  this.status = "Acknowledged";
  this.resolved_by = userId;
  this.resolved_at = new Date();
  return this.save();
};

// Resolve an alert (final state — no further changes)
AlertSchema.methods.resolve = async function (userId, notes = "") {
  this.status = "Resolved";
  this.resolved_by = userId;
  this.resolved_at = new Date();
  this.resolution_notes = notes;
  return this.save();
};

// ── Static methods ─────────────────────────────────────────
// Generates the next sequential alert_id from the highest existing
// one, rather than from a total document count — a count-based
// generator collides as soon as any alert is deleted (or the
// sequence has any gap), since the count no longer matches the
// highest id actually in use.
AlertSchema.statics.generateNextId = async function () {
  const latest = await this.findOne().sort({ alert_id: -1 }).select("alert_id");
  if (!latest) return "ALT-0001";
  const num = parseInt(latest.alert_id.replace("ALT-", ""), 10) + 1;
  return `ALT-${String(num).padStart(4, "0")}`;
};

// Fetch all active alerts for a barangay (used by nurse + barangay admin)
AlertSchema.statics.getActiveByBarangay = function (barangayId) {
  return this.find({
    barangay_id: barangayId,
    status: { $in: ["Active", "Acknowledged"] },
  }).sort({ created_at: -1 });
};

// Fetch all active escalation alerts (used by super admin dashboard)
AlertSchema.statics.getActiveEscalations = function () {
  return this.find({
    alert_type: { $in: ["Escalation L1", "Escalation L2", "Escalation L3"] },
    status: { $in: ["Active", "Acknowledged"] },
  }).sort({ escalation_level: -1, created_at: -1 });
};

// Fetch all active alerts visible to a specific role
AlertSchema.statics.getActiveByRole = function (role, barangayId = null) {
  const query = {
    target_roles: role,
    status: { $in: ["Active", "Acknowledged"] },
  };
  // super_admin and patc see all barangays — no barangay filter
  if (barangayId && role !== "super_admin" && role !== "patc") {
    query.barangay_id = barangayId;
  }
  return this.find(query).sort({ severity: -1, created_at: -1 });
};

// ── toJSON cleanup ─────────────────────────────────────────
AlertSchema.set("toJSON", {
  virtuals: true,
  versionKey: false,
  transform: (doc, ret) => {
    delete ret._id;
    delete ret.id;
    return ret;
  },
});

const Alert = model("Alert", AlertSchema);

export default Alert;
